# Site settings
title: Tahiti
subtitle: DevOps
email: contact@devops.pf
description: POUR QUE DEV ET OPS SE COMPRENNENT, ET POUR FAIRE PRENDRE CONSCIENCE DE L'IMPORTANCE SOCIALE DE L'INFORMATIQUE.
baseurl: ""
url: "http://127.0.0.1"
author: devops.pf team
street_address: BP 62063
city: Faaa
state: Tahiti
zip_code: 98702
country: Polynésie Française
phone: (+689) 87 344 610

# Social settings
500px_url:
facebook_url: http://fb.me/TahitiDevOps
github_url: https://github.com/tahitidevops
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: http://tahitidevops.slack.com
twitter_url: https://twitter.com/tahitidevops
meetup_url: https://www.meetup.com/TahitiDevOps

# Build settings
markdown: kramdown

# CSS build settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README
  - editorial_jekyll_theme.gemspec
  - docker
  - Dockerfile
