# Site settings
title: Tahiti
subtitle: DevOps
email: contact@tahiti.dev
description: POUR QUE DEV ET OPS SE COMPRENNENT, ET POUR FAIRE PRENDRE CONSCIENCE DE L'IMPORTANCE SOCIALE DE L'INFORMATIQUE.
baseurl: ""
url: "https://www.tahiti.dev"
author: tahiti.dev
street_address: BP 40855
city: Papeete
state: Tahiti
zip_code: 98713
country: Polynésie Française
phone: (+689) 87 344 610

# Social settings
500px_url:
facebook_url: https://fb.me/TahitiDevOps
github_url: https://github.com/tahitidevops
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://tahitidevops.slack.com
twitter_url: https://twitter.com/tahitidevops
meetup_url: https://www.meetup.com/TahitiDevOps
conference_server: https://meet.polynesie-francaise.pf/devops

# Build settings
markdown: kramdown
destination: public

# CSS build settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README
  - editorial_jekyll_theme.gemspec
  - docker
  - Dockerfile
