name: github pages

on:
  push:
    branches:
      - prod
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build Jekyll
        uses: helaili/jekyll-action@v2
        with:
          build_only: true

      - name: rsync deployments on tahiti.dev
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: ./public/
          remote_path: /home/tahiti_dev/tahiti.dev
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      
      - name: rsync deployments on devops.pf
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: ./public/
          remote_path: /home/tahiti_dev/devops.pf
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}